# --- BASE IMAGE ---
# We use a CUDA 12.1.1 base image. This is compatible with your host's CUDA 13.0 driver
# and is required by modern PyTorch builds (which are not yet built for CUDA 13.0).
# We've also updated to Ubuntu 22.04, as it's more modern.
FROM nvidia/cuda:13.0.1-cudnn-devel-ubuntu22.04

# --- ENVIRONMENT & TIMEZONE ---
ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# --- SYSTEM DEPENDENCIES ---
# Updated for Ubuntu 22.04 (e.g., libgtk-3-dev, qtbase5-dev)
# Added 'apt-get clean' to reduce image size
RUN apt-get update --fix-missing && \
    apt-get install -y \
    libgtk-3-dev \
    wget bzip2 ca-certificates curl git vim tmux g++ gcc build-essential cmake checkinstall gfortran \
    libjpeg-dev libtiff-dev pkg-config yasm \
    # Corrected libdc1394-22-dev to libdc1394-dev for Ubuntu 22.04
    libavcodec-dev libavformat-dev libswscale-dev libdc1394-dev libxine2-dev libv4l-dev \
    qtbase5-dev libgtk-3-dev libtbb-dev libatlas-base-dev \
    libfaac-dev libmp3lame-dev libtheora-dev libvorbis-dev libxvidcore-dev \
    libopencore-amrnb-dev libopencore-amrwb-dev x264 v4l-utils \
    libprotobuf-dev protobuf-compiler libgoogle-glog-dev libgflags-dev libgphoto2-dev \
    libhdf5-dev doxygen libflann-dev libboost-all-dev proj-data libproj-dev \
    libyaml-cpp-dev cmake-curses-gui libzmq3-dev freeglut3-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# --- PYBIND11 ---
RUN cd / && git clone https://github.com/pybind/pybind11 &&\
    cd pybind11 && git checkout v2.10.0 &&\
    mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DPYBIND11_INSTALL=ON -DPYBIND11_TEST=OFF &&\
    make -j$(nproc) && make install && \
    cd / && rm -rf /pybind11

# --- EIGEN ---
RUN cd / && wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz &&\
    tar xvzf ./eigen-3.4.0.tar.gz &&\
    cd eigen-3.4.0 &&\
    mkdir build &&\
    cd build &&\
    cmake .. &&\
    make install && \
    cd / && rm -rf /eigen-3.4.0 /eigen-3.4.0.tar.gz

# --- MINICONDA ---
RUN cd / && wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /miniconda.sh && \
    /bin/bash /miniconda.sh -b -p /opt/conda &&\
    rm /miniconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh &&\
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc &&\
    # Accept Anaconda Terms of Service to fix build error
    /opt/conda/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    /opt/conda/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r && \
    /opt/conda/bin/conda update -n base -c defaults conda -y &&\
    # Updated to Python 3.10 for better library compatibility
    /opt/conda/bin/conda create -n my python=3.10 -y

# --- CONDA ENVIRONMENT ACTIVATION ---
# This setup ensures all subsequent RUN commands use the 'my' conda environment
SHELL ["/bin/bash", "--login", "-c"]
RUN echo "conda activate my" >> ~/.bashrc
# Fixed legacy ENV format
ENV PATH="/opt/conda/envs/my/bin:$PATH"

# --- PYTORCH ---
# Install modern PyTorch, torchvision, and torchaudio compiled for CUDA 12.1
# NOTE: When PyTorch eventually releases wheels for CUDA 13.0, you would
# change "cu121" to "cu130" (or similar) here.
RUN pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/pre/cu130

# --- PYTHON LIBRARIES (from source) ---
RUN pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"

RUN cd / && git clone --recursive https://github.com/NVIDIAGameWorks/kaolin
RUN cd /kaolin && FORCE_CUDA=1 python setup.py develop

RUN cd / && git clone https://github.com/NVlabs/nvdiffrast
RUN cd /nvdiffrast && pip install .

# --- OTHER PYTHON LIBRARIES (pip) ---
RUN pip install \
    scipy \
    joblib \
    scikit-learn \
    ruamel.yaml \
    trimesh \
    pyyaml \
    opencv-python \
    imageio \
    open3d \
    transformations \
    warp-lang \
    einops \
    kornia \
    pyrender

ENV OPENCV_IO_ENABLE_OPENEXR=1

RUN pip install \
    scikit-image \
    meshcat \
    webdataset \
    omegaconf \
    pypng \
    roma \
    seaborn \
    opencv-contrib-python \
    openpyxl \
    wandb \
    imgaug \
    Ninja \
    xlsxwriter \
    timm \
    albumentations \
    xatlas \
    rtree \
    nodejs \
    jupyterlab \
    objaverse \
    g4f \
    ultralytics==8.0.120 \
    pycocotools \
    videoio \
    numba

# --- OTHER PYTHON LIBRARIES (conda) ---
RUN conda install -y -c anaconda h5py

# --- FINAL SETUP ---
ENV SHELL=/bin/bash
RUN ln -sf /bin/bash /bin/sh

